#!/usr/bin/env python3
"""Enforce the commit message contract described in .gitmessage.

Conventional Commits 1.0.0, with the repository's own constraints: an allowed
type, an optional scope, an optional '!' for a breaking change, and a subject
that is imperative, lower-case and at most 100 characters.

Usage:
    check_commit_messages.py <base-ref> <head-ref>

The range is exclusive of <base-ref>, matching ``git log base..head``.

Commits authored by Dependabot are exempt: their subjects are generated by
Dependabot itself, and the repository already configures the prefixes it uses
in .github/dependabot.yml.
"""

from __future__ import annotations

import re
import subprocess
import sys

ALLOWED_TYPES = (
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
)

MAX_SUBJECT_LENGTH = 100

SUBJECT_PATTERN = re.compile(
    r"^(?P<type>[a-z]+)"
    r"(?:\((?P<scope>[a-z0-9][a-z0-9._/-]*)\))?"
    r"(?P<breaking>!)?"
    r": (?P<description>.+)$"
)

# Commits GitHub itself creates, which no author can reformat.
EXEMPT_SUBJECT_PREFIXES = ("Merge pull request ", "Merge branch ", "Revert \"")
EXEMPT_AUTHORS = ("dependabot[bot]", "dependabot-preview[bot]", "github-actions[bot]")

RECORD_SEPARATOR = "\x1e"
UNIT_SEPARATOR = "\x1f"


def commits(base: str, head: str) -> list[tuple[str, str, str]]:
    """Returns (sha, author, subject) for each commit in base..head."""
    output = subprocess.run(
        [
            "git",
            "log",
            f"--format=%H{UNIT_SEPARATOR}%an{UNIT_SEPARATOR}%s{RECORD_SEPARATOR}",
            f"{base}..{head}",
        ],
        check=True,
        capture_output=True,
        text=True,
    ).stdout

    records = []
    for record in output.split(RECORD_SEPARATOR):
        record = record.strip("\n")
        if not record:
            continue
        sha, author, subject = record.split(UNIT_SEPARATOR, 2)
        records.append((sha, author, subject))
    return records


def problems_with(subject: str) -> list[str]:
    found: list[str] = []

    if len(subject) > MAX_SUBJECT_LENGTH:
        found.append(f"subject is {len(subject)} characters; the limit is {MAX_SUBJECT_LENGTH}")

    match = SUBJECT_PATTERN.match(subject)
    if match is None:
        found.append("subject does not match '<type>[optional scope][!]: <description>'")
        return found

    commit_type = match.group("type")
    if commit_type not in ALLOWED_TYPES:
        found.append(f"type '{commit_type}' is not one of: {', '.join(ALLOWED_TYPES)}")

    description = match.group("description")
    if description != description.lstrip():
        found.append("description has leading whitespace")
    if description.endswith("."):
        found.append("description ends with a full stop")
    if description[:1].isupper():
        found.append("description starts with a capital letter; it should be lower-case")

    return found


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    base, head = argv[1], argv[2]
    failures: list[str] = []
    checked = 0

    for sha, author, subject in commits(base, head):
        if author in EXEMPT_AUTHORS or subject.startswith(EXEMPT_SUBJECT_PREFIXES):
            continue
        checked += 1
        found = problems_with(subject)
        if found:
            failures.append(f"{sha[:12]} {subject}\n" + "\n".join(f"      - {item}" for item in found))

    if failures:
        print("Commit message check failed:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        print(
            "\nSee .gitmessage and CONTRIBUTING.md. Set the template locally with:\n"
            "    git config commit.template .gitmessage",
            file=sys.stderr,
        )
        return 1

    print(f"{checked} commit message(s) conform to .gitmessage.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
