#!/usr/bin/env python3
"""Validate commit messages against Conventional Commits 1.0.0.

The convention is what makes the history mechanically readable: it drives
changelog generation and lets a reviewer see the nature and blast radius of a
change from ``git log`` alone. The rules encoded here are the ones stated in
``.gitmessage`` and ``AGENTS.md``.

Enforced invariants, per commit:

1. The subject matches ``<type>[optional scope][!]: <description>``.
2. The type is one of the allowed set.
3. The description is non-empty, lower-case, imperative, and has no trailing period.
4. The whole subject line is at most 100 characters.
5. A breaking change is declared consistently: ``!`` in the subject and a
   ``BREAKING CHANGE:`` footer must agree with each other.
6. The line after the subject is blank, so the body is a real paragraph rather
   than an accidental continuation.

Merge and revert commits generated by tooling are skipped, as are commits
authored by Dependabot, which is explicitly exempt.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys

ALLOWED_TYPES = (
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
)

MAX_SUBJECT_LENGTH = 100

SUBJECT = re.compile(
    r"^(?P<type>[a-z]+)"
    r"(?:\((?P<scope>[^()\r\n]+)\))?"
    r"(?P<breaking>!)?"
    r": (?P<description>.+)$"
)

# Commits created by tooling rather than authored by a contributor.
SKIP_PREFIXES = ("Merge ", "Revert ", "fixup! ", "squash! ")

# Bots exempt from the convention. Dependabot is exempt by policy; it composes
# its own subjects and we do not control them.
EXEMPT_AUTHORS = ("dependabot[bot]", "dependabot-preview[bot]", "github-actions[bot]")

RECORD_SEPARATOR = "\x1e"
FIELD_SEPARATOR = "\x1f"


def read_commits(revision_range: str) -> list[tuple[str, str, str]]:
    """Return (sha, author, message) for each commit in the range."""
    result = subprocess.run(
        [
            "git",
            "log",
            f"--format=%H{FIELD_SEPARATOR}%an{FIELD_SEPARATOR}%B{RECORD_SEPARATOR}",
            revision_range,
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    commits = []
    for record in result.stdout.split(RECORD_SEPARATOR):
        record = record.strip("\n")
        if not record.strip():
            continue
        sha, author, message = record.split(FIELD_SEPARATOR, 2)
        commits.append((sha, author, message))
    return commits


def validate(sha: str, message: str) -> list[str]:
    """Return the rule violations for a single commit message."""
    problems: list[str] = []
    lines = message.splitlines()
    if not lines:
        return [f"{sha[:8]}: empty commit message"]

    subject = lines[0].rstrip()

    if len(subject) > MAX_SUBJECT_LENGTH:
        problems.append(
            f"{sha[:8]}: subject is {len(subject)} characters, "
            f"maximum is {MAX_SUBJECT_LENGTH}"
        )

    match = SUBJECT.match(subject)
    if match is None:
        problems.append(
            f"{sha[:8]}: subject does not match '<type>[optional scope][!]: <description>'\n"
            f"           got: {subject!r}"
        )
        return problems

    commit_type = match.group("type")
    description = match.group("description").strip()

    if commit_type not in ALLOWED_TYPES:
        problems.append(
            f"{sha[:8]}: type {commit_type!r} is not allowed; "
            f"use one of: {', '.join(ALLOWED_TYPES)}"
        )

    if not description:
        problems.append(f"{sha[:8]}: description is empty")
    else:
        if description.endswith("."):
            problems.append(f"{sha[:8]}: description must not end with a period")
        first = description[0]
        # Allow a leading non-letter (a path, a version, a quoted identifier);
        # only reject an obviously capitalised word.
        if first.isalpha() and first.isupper():
            problems.append(f"{sha[:8]}: description must start lower-case")

    # A breaking change must be signalled the same way in both places, otherwise
    # release tooling and human readers disagree about the severity.
    body = "\n".join(lines[1:])
    has_bang = match.group("breaking") == "!"
    has_footer = re.search(r"^BREAKING[ -]CHANGE:", body, re.MULTILINE) is not None
    if has_bang and not has_footer:
        problems.append(
            f"{sha[:8]}: subject is marked '!' but there is no 'BREAKING CHANGE:' footer"
        )
    if has_footer and not has_bang:
        problems.append(
            f"{sha[:8]}: has a 'BREAKING CHANGE:' footer but the subject is not marked '!'"
        )

    if len(lines) > 1 and lines[1].strip():
        problems.append(f"{sha[:8]}: the line after the subject must be blank")

    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "range",
        nargs="?",
        default="HEAD~1..HEAD",
        help="Git revision range to validate (default: HEAD~1..HEAD)",
    )
    args = parser.parse_args()

    try:
        commits = read_commits(args.range)
    except subprocess.CalledProcessError as exc:
        print(f"Could not read commits for {args.range!r}: {exc.stderr}", file=sys.stderr)
        return 2

    problems: list[str] = []
    checked = 0

    for sha, author, message in commits:
        subject = message.splitlines()[0] if message.splitlines() else ""
        if author in EXEMPT_AUTHORS:
            print(f"  skipped {sha[:8]} (exempt author: {author})")
            continue
        if subject.startswith(SKIP_PREFIXES):
            print(f"  skipped {sha[:8]} (tooling-generated commit)")
            continue
        checked += 1
        problems.extend(validate(sha, message))

    if problems:
        print("Commit message validation failed:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print(
            "\nSee CONTRIBUTING.md and .gitmessage. "
            "Load the template with: git config commit.template .gitmessage",
            file=sys.stderr,
        )
        return 1

    print(f"Commit message validation passed ({checked} commit(s) checked).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
